application: sigfxfx
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
- name: django
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: djangoappengine.main.application

