application: sigfxfx
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

libraries:
- name: django
  version: latest

handlers:
- url: /tasks/expiry
  script: djangoappengine.main.application
  login: admin
  secure: always

- url: /static
  static_dir: static

- url: /.*
  script: djangoappengine.main.application
  secure: always


