application: foo-barketplace
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

libraries:
- name: django
  version: latest

handlers:
- url: /tasks/expiry
  script: djangoappengine.main.application
  login: admin
  secure: always

- url: /static
  static_dir: static

- url: /myprofile/.+
  secure: always
  script: djangoappengine.main.application

- url: /admin/.*
  secure: always
  script: djangoappengine.main.application

- url: /sell/.+
  secure: always
  script: djangoappengine.main.application

- url: /item/\d+/.*
  secure: always
  script: djangoappengine.main.application

- url: /.*
  script: djangoappengine.main.application
